### ISSUE TITLE
Сделать еще более понятным запрос на слияние

### ISSUE THREAD

**Issue by azotov** [realtim/mmb#273]
Увы, количество пользователей, которые ошибочно отправляют запрос на слияние, когда пытаются добавить нового участника в свою команду, не уменьшается. Надо сделать отдельную промежуточную страницу, которая показывается при попытке отправить запрос на слияние. На этой странице надо:
1)написать про то, что понимается под слиянием пользователей, и что нужно сделать, если нужно добавить еще одного участника в команду.
2)написать про то, что во время ммб заявки на слияние не обрабатываются и будут отложены до его окончания.
Ну и еще раз спросить подтверждение на отправку заявки на слияние.

**Comment by leonidfishkis** [comment]
Я бы предложил:1) Написать в ЖЖ прямо сейчас про эти стандартные ситуации2) Посмотреть, сколько реальных объединений и если мало, то закрыть для пользователей эту опцию  - оставить на администраторов. 3)  переписать интерфейс и логику объединения команд, чтобы пользователи могли сами это делать



-------- Исходное сообщение --------
От: Alexander Zotov <notifications@github.com> 
Дата: 31.10.2017  9:06  (GMT+01:00) 
Кому: realtim/mmb <mmb@noreply.github.com> 
Копия: Subscribed <subscribed@noreply.github.com> 
Тема: [realtim/mmb] Сделать еще более понятным запрос на слияние (#273) 

Увы, количество пользователей, которые ошибочно отправляют запрос на слияние, когда пытаются добавить нового участника в свою команду, не уменьшается. Надо сделать отдельную промежуточную страницу, которая показывается при попытке отправить запрос на слияние. На этой странице надо:

1)написать про то, что понимается под слиянием пользователей, и что нужно сделать, если нужно добавить еще одного участника в команду.

2)написать про то, что во время ммб заявки на слияние не обрабатываются и будут отложены до его окончания.

Ну и еще раз спросить подтверждение на отправку заявки на слияние.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/realtim/mmb","title":"realtim/mmb","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/realtim/mmb"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Сделать еще более понятным запрос на слияние (#273)"}],"action":{"name":"View Issue","url":"https://github.com/realtim/mmb/issues/273"}}}

**Comment by azotov** [comment]
1)Увы, те, кто наступают на эти грабли, не читают внимательно ни ЖЖ, ни FAQ.
2)Перед этим ммб было 46 заявок на слияние пользователей. Из них только 9 - настоящие слияния дублей, все остальные - это неудачные попытки добавить нового пользователя в команду с помощью слияния пользователей. Совсем закрывать для пользователей возможность отправки заявки не хочется - все-таки она используется по делу достаточно часто, да и мы сами хотим стимулировать и облегчить пользователям ликвидацию дублей.
3)Не понял, при чем тут объединение команд. Участники путают эту страницу не с объединением команд после ммб, а с добавлением участников в команду перед ммб.

**Comment by leonidfishkis** [comment]
2) Ну можно посмотреть, м.б. можно быстро закрыть слияние на время ММБ (есть хотя бы один ММБ в статусе, отличном от  RaidClose) и тогда автоматически число ошибок сократится.

3) не в тему написал - это скорее к обсуждению в рассылке разработчиков про возможные нововведения

**Comment by leonidfishkis** [comment]
Изменил проверку для уже участвующих ранее в объединении.
Добавил проверку на отсутствие активных ммб

**Comment by leonidfishkis** [comment]
Я закрываю задачу:  за 2020 год было два успешных и 0 отклонённых, и в 2021 году я не вижу пока проблем: одно подтверждённое слияние, 0 отклонённых и два разъяснения, что слияние не работает во время активного ммб.
